name: 'Workflow Cleanup Action'
description: 'An action to clean up old workflow runs across repositories.'
author: 'gesslar <karahd@gmail.com>'
inputs:
  pat:
    description: 'Personal Access Token (classic) with repo and workflow scopes'
    required: true
  repo_owner:
    description: 'Owner of the repositories'
    required: true
    default: ${{ github.repository_owner }}
  target_cleanup_repos:
    description: 'Comma-separated list of repositories to include'
    required: false
  target_ignore_repos:
    description: 'Comma-separated list of repositories to exclude'
    required: false
  days_threshold:
    description: 'Number of days to keep workflow runs'
    required: false
    default: '7'
  notification_webhook_url:
    description: 'Webhook URL for sending notifications'
    required: false
runs:
  using: 'composite'
  steps:
    - name: Execute Cleanup Script
      shell: bash
      run: ./cleanup.sh
      env:
        PAT: ${{ inputs.pat }}
        REPO_OWNER: ${{ inputs.repo_owner }}
        TARGET_CLEANUP_REPOS: ${{ inputs.target_cleanup_repos }}
        TARGET_IGNORE_REPOS: ${{ inputs.target_ignore_repos }}
        DAYS_THRESHOLD: ${{ inputs.days_threshold }}
        NOTIFICATION_WEBHOOK_URL: ${{ inputs.notification_webhook_url }}
