name: 'Workflow Cleanup Action'
description: 'An action to clean up old workflow runs across repositories.'
author: 'gesslar <karahd@gmail.com>'
inputs:
  token:
    description: 'Personal Access Token with repo and workflow scopes'
    required: true
  repo_owner:
    description: 'Owner of the repositories'
    required: true
    default: ${{ github.repository_owner }}
  target_cleanup_repos:
    description: 'Comma-separated list of repositories to include'
    required: false
  target_ignore_repos:
    description: 'Comma-separated list of repositories to exclude'
    required: false
  days_threshold:
    description: 'Number of days to keep workflow runs'
    required: false
    default: '7'
  notification_webhook_type:
    description: 'Type of notification webhook'
    required: false
    default: 'discord'
  notification_webhook_url:
    description: 'Webhook URL for sending notifications'
    required: false
  debug:
    description: 'Enable debug mode'
    required: false
    default: 'false'
runs:
  using: 'node20'
  main: 'dist/index.js'
branding:
  color: 'green'
  icon: 'trash'
