name: Compile and Release Action

on:
  workflow_run:
    workflows: ["Generate New Tag"]
    types:
      - completed

jobs:
  compile_and_release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Download New Tag Artifact
        uses: actions/download-artifact@v4
        with:
          name: new_tag

      - name: Read Tag from File
        id: read_tag
        run: |
          TAG=$(cat new_tag.txt)
          echo "NEW_TAG=${TAG}" >> $GITHUB_ENV

      - name: Install dependencies
        run: npm install

      - name: Build action using NCC
        run: npm run build

      - name: Archive dist folder
        run: |
          mkdir -p artifacts
          zip -r artifacts/action.zip dist

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.NEW_TAG }}
          release_name: Release ${{ env.NEW_TAG }}
          body_path: ./README.md
          draft: false
          prerelease: false
