name: Bump Version and Create Tag

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  tag_version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Read version from package.json
        id: get_version
        run: |
          CURRENT_VERSION=$(node -p "require('./package.json').version")
          echo "CURRENT_VERSION=${CURRENT_VERSION}" >> $GITHUB_ENV

      - name: Check for existing tag
        id: check_tag
        run: |
          TAG_EXISTS=$(git tag -l "v${{ env.CURRENT_VERSION }}")
          echo "TAG_EXISTS=${TAG_EXISTS}" >> $GITHUB_ENV
          if [ -z "$TAG_EXISTS" ]; then
            echo "Tag does not exist for version ${{ env.CURRENT_VERSION }}. Creating tag."
            git config user.name "github-actions"
            git config user.email "github-actions@github.com"
            git tag "v${CURRENT_VERSION}"
            git push origin "v${CURRENT_VERSION}"
          else
            echo "Tag already exists for version ${{ env.CURRENT_VERSION }}. Skipping tag creation."
            exit 0
          fi
