name: Release

on:
  pull_request:
    types: [closed]
    branches: [main]
  workflow_dispatch:

jobs:
  Release:
    if: ${{ github.event_name == 'workflow_dispatch' || github.event.pull_request.merged == true }}
    uses: gesslar/Maint/.github/workflows/ReleaseAction.yaml@main
    secrets: inherit
    permissions:
      contents: write
